### PR TITLE
Adding stamp usage to the EU controller

### PR DESCRIPTION
**Pull request by neoPix**
## Warnings

- pin and token regeneration have not been tested

## Good news

- Removes the runtime dep to the JVM from https://github.com/Hacksore/bluelinky/pull/104

## Notes

- Kuvork `APP_ID = '693a33fa-c117-43f2-ae3b-61a02d24f417'`

## How

- Generation a collection of stamps for the users to use (vie a docker image)
- Stamps are used randomly at run time

So technically, any languages calling the same command could use it.

### CODE REVIEW

**Comment by SondreNjaastad** [comment]
I´m a little confused on this PR, do we need all these external .so files and to run them via nodejs execute command? This wont adapt nicely with some platforms like Angular etc

**Comment by andig** [comment]
It sounds like the new logic hasn‘t been reverse-engineered and is only available as native lib?

**Comment by neoPix** [comment]
@SondreNjaastad Those are only used to generate a large amount a stamp file. The person responsible of the build (or CI), at runtime they wont even be here.

NB: It will work as long as the server side `stamp` validation stay as is and still let our automation work. But we will have do dig deeper.

**Comment by PierreLevres** [comment]
Bluelink App_id = 99cfff84-f4e2-4be8-a5ed-e5b755eb6581

**Pull request merged**
