### PR TITLE
[EU] Use both auth strategies

### PR DESCRIPTION
**Pull request by neoPix**
Uses
- The new account strategy first
- If it fails it will use the legacy strategy
  - The failure logs an error but goes on

### CODE REVIEW

**Comment by gruijter** [comment]
I have multipe Homey users now complaining there login doesn't work anymore since Bluelinky was updated to 7.1.0. I have advised them to check if they migrated their account to Kia/Hyundai. But it would be very welcome to have a bluelinky npm update that solves the issue for them if they are still using the old uvo/bluelink account.

**Comment by neoPix** [comment]
Here two changes might help,
- The username & password are now serialized (so special character will also work).
- A fallback is now possible

**Comment by mpucherSmIT** [comment]
It seems, my legacy bluelink account stopped working yesterday at 4 o'clock in the afternoon. As the new hyundai account requires special characters it fails (400 bad request) with the new credentials (and bluelinky v7.1.0).

Could you please release the change?

**Comment by PierreLevres** [comment]
What if you would just use ! as a special character, that ought to work I suppose?

**Comment by mpucherSmIT** [comment]
> What if you would just use ! as a special character, that ought to work I suppose?

Thank you, that did the trick!

**Pull request merged**
