### PR TITLE
Fetching the stamps from an external source

### PR DESCRIPTION
**Pull request by neoPix**
## Done

- Fetching the stamps from a github repo (https://github.com/neoPix/bluelinky-stamps for now)
- Caching the data

### CODE REVIEW

**Comment by Hacksore** [comment]
@neoPix what might be a good idea is we could allow a way to specify any remote/local stamp destination for the payload. Perhaps some method to specify a local `file://` or a remote hosted URL with a JSON object.

That way if I'm not able to get it updated users can input that themselves, let me know what you think about that approach.

**Comment by PierreLevres** [comment]
Sounds very good. Why not use a new entry In the bluelinky config object for that url?

But where to do the conversion of the plain text output of stamps to a json object? Wouldn’t it be easier to build that into bluelinky login/initialization ?

That way all you need are the stamps generated by you docker lib, or any other running docker, fed into text files hosted anywhere. I would prefer not changing the docker output.

**Comment by neoPix** [comment]
@Hacksore I could add it as an option on EU elements. Could use `fs.readFile()` when `file://` is found and got (as is) for anything http. If not specified it will use a default http repository.

@PierreLevres It would be very heavy to force docker into the login process, and would break the compat with some systems. With this change, the docker part won't be changed.

**Comment by PierreLevres** [comment]
I did not mean to run docker in the login process. Just to use a docker generated output file (plain text and not json) in the login process.

**Comment by neoPix** [comment]
@PierreLevres Oh, ok. I won't change this in this PR, but it can easily be done if we chose to do it.

**Comment by neoPix** [comment]
@Hacksore I updated the code to add yet an other EU option, and added some documentation about it.
Since english is not my main language, it might be clumsy.

**Comment by mpucherSmIT** [comment]
Hi, I updated to 7.3.0 and still get 401 'Invalid request value - Invalid Application Id.'

Do I have to change config files?

**Pull request merged**
