### PR TITLE
Update european.vehicle.ts

### PR DESCRIPTION
**Pull request by PierreLevres**
Added return statements to 'setchargetarget' and 'setnavigation'

### CODE REVIEW

**Comment by neoPix** [comment]
Since JavaScript will return `undefined` by default, apart for adding logs, this PR does not much.

**Comment by Hacksore** [comment]
I agree with @neoPix to an extent but we should return something truthy on a successful call. 

Maybe returning some message saying the call was successful is what we want.

**Comment by PierreLevres** [comment]
In the module I see a third way of returning:
return response.body;

Sometimes the return is preceded by a check if (response.statusCode === 200) and if no success a log-item "Something went wrong
Sometimes the return is preceded by a log-item such as: logger.info(`Did blah blah for vehicle ${this.vehicleConfig.id}`); or logger.debug(`Vehicle ${this.vehicleConfig.id} blahblahed`);

It was tempting to start rewriting and making it more consistent, but I don't know what programming guidelines you guys are following...

**Comment by Hacksore** [comment]
@PierreLevres I agree it's not very consistent in all areas 😅

**Pull request closed without merging**
